### ISSUE TITLE
cloud-init status: error

### ISSUE THREAD

**Issue by carlosgrillet** [identiops/terraform-hcloud-k3s#18]
I was trying to deploy kubernetes all this time in hetzner but I didn't took the time to do it manually. When I saw this repo I thought "this is my chance", after some minutes of trubleshoting I was able to run `terraform apply`, but after the deployment finish the vm's where up but the kubernetes configuration not. Here are the last lines of the `/var/log/cloud-init.log` file.

```log
2024-11-08 21:51:57,905 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/55387542/sem/config_scripts_user - wb: [644] 24 bytes
2024-11-08 21:51:57,906 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/55387542/sem/config_scripts_user'>)
2024-11-08 21:51:57,906 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/runcmd'] with allowed return codes [0] (shell=False, capture=False)
2024-11-08 21:52:06,573 - subp.py[DEBUG]: ['/var/lib/cloud/instance/scripts/runcmd'] took 8.6s to run
2024-11-08 21:52:06,574 - subp.py[DEBUG]: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/runcmd']
Exit code: 100
Reason: -
Stdout: -
Stderr: -
2024-11-08 21:52:06,574 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2024-11-08 21:52:06,574 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2024-11-08 21:52:06,574 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
2024-11-08 21:52:06,574 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 286, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 60, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
    subp.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 390, in runparts
    raise RuntimeError(
RuntimeError: Runparts: 1 failures (runcmd) in 1 attempted commands
2024-11-08 21:52:06,577 - modules.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2024-11-08 21:52:06,578 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2024-11-08 21:52:06,578 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/55387542/sem/config_ssh_authkey_fingerprints - wb: [644] 24 bytes
2024-11-08 21:52:06,578 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/55387542/sem/config_ssh_authkey_fingerprints'>)
2024-11-08 21:52:06,579 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2024-11-08 21:52:06,579 - modules.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2024-11-08 21:52:06,579 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2024-11-08 21:52:06,579 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/55387542/sem/config_keys_to_console - wb: [644] 23 bytes
2024-11-08 21:52:06,579 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/55387542/sem/config_keys_to_console'>)
2024-11-08 21:52:06,579 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] with allowed return codes [0] (shell=False, capture=True)
2024-11-08 21:52:06,644 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2024-11-08 21:52:06,644 - modules.py[DEBUG]: Running module install-hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2024-11-08 21:52:06,644 - handlers.py[DEBUG]: start: modules-final/config-install-hotplug: running config-install-hotplug with frequency once-per-instance
2024-11-08 21:52:06,645 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/55387542/sem/config_install_hotplug - wb: [644] 24 bytes
2024-11-08 21:52:06,645 - helpers.py[DEBUG]: Running config-install-hotplug using lock (<FileLock using file '/var/lib/cloud/instances/55387542/sem/config_install_hotplug'>)
2024-11-08 21:52:06,645 - util.py[DEBUG]: Reading from /var/lib/cloud/hotplug.enabled (quiet=False)
2024-11-08 21:52:06,645 - util.py[DEBUG]: File not found: /var/lib/cloud/hotplug.enabled
2024-11-08 21:52:06,645 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2024-11-08 21:52:06,646 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=hotplug
2024-11-08 21:52:06,646 - cc_install_hotplug.py[DEBUG]: Skipping hotplug install, not enabled
2024-11-08 21:52:06,646 - handlers.py[DEBUG]: finish: modules-final/config-install-hotplug: SUCCESS: config-install-hotplug ran successfully
2024-11-08 21:52:06,646 - modules.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2024-11-08 21:52:06,646 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2024-11-08 21:52:06,646 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f2516f732b0>)
2024-11-08 21:52:06,646 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-11-08 21:52:06,646 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2024-11-08 21:52:06,651 - util.py[DEBUG]: Cloud-init v. 24.2-0ubuntu1~22.04.1 finished at Fri, 08 Nov 2024 21:52:06 +0000. Datasource DataSourceHetzner.  Up 138.41 seconds
2024-11-08 21:52:06,651 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 68 bytes
2024-11-08 21:52:06,654 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2024-11-08 21:52:06,654 - main.py[DEBUG]: Ran 12 modules with 1 failures
2024-11-08 21:52:06,654 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-11-08 21:52:06,654 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2024-11-08 21:52:06,655 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpt_jubrns) - w: [644] 1328 bytes/chars
2024-11-08 21:52:06,655 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp1s6whks2) - w: [644] 164 bytes/chars
2024-11-08 21:52:06,655 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2024-11-08 21:52:06,655 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-11-08 21:52:06,656 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2024-11-08 21:52:06,656 - util.py[DEBUG]: cloud-init mode 'modules' took 8.920 seconds (8.92)
2024-11-08 21:52:06,656 - handlers.py[DEBUG]: finish: modules-final: FAIL: running modules for final
```

**Comment by jceb** [comment]
Thank you for reporting the issue. I'm currently very busy with other topics, hoping to get to it soon.

**Comment by jceb** [comment]
Would you try again. I just updated the configuration to support Ubuntu 24.04.

**Comment by milosmns** [comment]
Hey @jceb 👋 I have the same issue now – Is there a way I can debug this further? I'd like to understand more about what's going on (also on Ubuntu 24.04)…

**Comment by jceb** [comment]
I noticed that sometimes the init script fails without any detectable reason. @milosmns Would you try reexecuting the runcmd script? There is a description of how to find the script in the Reamdme's troubleshooting section.

**Comment by milosmns** [comment]
@jceb thanks for that pointer, it revealed some logs where I could see that the K3S version it was trying to download fails the setup (download hash/checksum URL for that version was invalid).

For reference, I was trying with: 

```terraform
default_image     = "ubuntu-24.04"
k3s_version       = "v1.32.2-k3s1"
```

It was reproducible on 3 consecutive attempts. I'll downgrade both to test again.

**Comment by milosmns** [comment]
Downgrading K3S to `v1.31.6-k3s1` helped, but hasn't resolved all the issues yet.

> Once SSH connection is established, double check that everything is working as expected:
>   - Did the node initialization finish successfully? cloud-init status

✅

>   - Is the cluster up and running? kubectl cluster-info

❌

```console
root@ah-system-00:~# cloud-init status
status: running

root@ah-system-00:~# kubectl cluster-info
Command 'kubectl' not found, did you mean:
  command 'kubectx' from deb kubectx (0.9.5-1ubuntu0.2)
Try: apt install <deb name>

root@ah-system-00:~#

Broadcast message from systemd-journald@appifyhub-system-00 (Sun 2025-03-09 14:30:57 UTC):

haproxy[2349]: proxy k8s has no server available!
```

Seemingly unrelated (but might be a consequence of the same issue), I see that one of the firewalls was not applied to a server. I could apply it manually from the console interface, but not sure if that's the right way to go. I would expect terraform to make those changes. Here's what it looks like for me (configured for 2 system and 2 worker nodes).

![Image](https://github.com/user-attachments/assets/fbcb99f2-eefb-436f-a9c4-505f3f0f72c0)

It's slightly inconvenient to test this, considering that it's the setup stage… I need to forget SSH hosts, terraform destroy, re-apply, etc. But I think I'm close now, and really appreciate you responding to the issues 🙏

**Comment by jceb** [comment]
The not applied firewall rule is expected, by default it's not applied - check `gateway_firewall_k8s_open` and the reason for it.

```bash
root@ah-system-00:~# cloud-init status
status: running
```

^^ the setup is still `running`.

I'd recommend you to not go for 2 control plane nodes. You need an uneven number. Go for 1 and 3 workers or just 3 control plane nodes. This will increase the availability of your cluster.

**Comment by milosmns** [comment]
Thanks for the pointers @jceb, makes sense. Again, much appreciated.

I've now changed the config as per your suggestion, and then destroyed & created all resources again. In the meantime I discovered a couple of other issues that were preventing me from setting up the cluster the way I wanted – but those have been corrected now and I'm happy to report that the initial setup is successful!

**Comment by jceb** [comment]
@milosmns glad to hear that you managed to get the cluster up and running. What were the other issues you ran into?

**Comment by milosmns** [comment]
It was a bunch of dumb mistakes on my part 🙂 

For example, as you can see [here](https://github.com/identiops/terraform-hcloud-k3s/issues/18#issuecomment-2708877856), I've used `-` instead of `+` for some reason when configuring the K3S version. Or another one, I forgot to enable/apply the firewall I asked you about, so `kubectl` couldn't find my remote clusters… both easily resolved, but it took some time to figure what's going on. Your input greatly helped and I was able to test this setup myself.
